### ISSUE TITLE
fix: Repos' style differs from Commits

### ISSUE THREAD

**Issue by yhakamay** [yhakamay/me#112]
Let's make them consistent

<details><summary>Repos</summary>
<p>

```css
.repos {
  .items {
    -webkit-mask-image: -webkit-gradient(
      linear,
      left top,
      left bottom,
      from(rgba(0, 0, 0, 1)),
      to(rgba(0, 0, 0, 0.6))
    );
    mask-image: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 1),
      rgba(0, 0, 0, 0.6)
    );

    .name {
      min-width: 48px;
    }

    .description {
      margin-top: 0.4rem;
      margin-bottom: 0.8rem;
      font-size: 0.8rem;
      opacity: 0.8;

      &.not_provided {
        font-style: italic;
        opacity: 0.5;
      }
    }
  }

  .more {
    margin-top: 0.6rem;
    opacity: 0.9;
  }
}
```

</p>
</details> 

<details><summary>Commits</summary>
<p>

```css
.commits {
  .items {
    -webkit-mask-image: -webkit-gradient(
      linear,
      left top,
      left bottom,
      from(rgba(0, 0, 0, 1)),
      to(rgba(0, 0, 0, 0.6))
    );
    mask-image: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 1),
      rgba(0, 0, 0, 0.6)
    );

    .title {
      min-width: 48px;
    }

    .message {
      margin-top: 0.4rem;
      opacity: 0.8;
    }

    .date_time {
      margin-top: 0.6rem;
      margin-bottom: 0.8rem;
      font-size: 0.8rem;
      opacity: 0.6;
    }
  }

  .more {
    margin-top: 0.6rem;
    opacity: 0.9;
  }
}
```

</p>
</details>
